# mapped_names = c("%26" = ' & ',
#                  '.' = '',
#                  'Pit, but edgy' = 'Dark Pit',
#                  'Dank Samus' = 'Dark Samus',
#                  'Educated Mario' =  'Dr Mario',
#                  'Duck Hunt Duo' = 'Duck Hunt',
#                  '^Dedede$' =  'King Dedede',
#                  'King K. Rool'  = 'King K Rool',
#                  'King KRool'  = 'King K Rool',
#                  'Megaman' = 'Mega Man',
#                  'Mii Swordspider' = 'Mii Swordfighter',
#                  'M. Game & Watch' = 'Mr Game & Watch',
#                  'PAC-MAN' = 'Pac Man',
#                  'Pac-Man' = 'Pac Man',
#                  'PACMAN' = 'Pac Man',
#                  'Pok%C3%A9mon Trainer' = 'Pokemon Trainer',
#                  'é'  = 'e',
#                  'R.O.B.' = 'Rob',
#                  'ROB' = 'Rob',
#                  'Rosalina' = 'Rosalina & Luma')
# 
mapped_names = c("Banjo%26Kazooie" = 'Banjo & Kazooie',
                 'Bowser Jr.' = 'Bowser Jr',
                 'Pit, but edgy' = 'Dark Pit',
                 'Dank Samus' = 'Dark Samus',
                 'Dr. Mario' = 'Dr Mario',
                 'Educated Mario' =  'Dr Mario',
                 'Duck Hunt Duo' = 'Duck Hunt',
                 '^Dedede$' =  'King Dedede',
                 'King K. Rool'  = 'King K Rool',
                 'King KRool'  = 'King K Rool',
                 'Megaman' = 'Mega Man',
                 'Mii Swordspider' = 'Mii Swordfighter',
                 'Mr. Game & Watch' = 'Mr Game & Watch',
                 'M. Game & Watch' = 'Mr Game & Watch',
                 'Mr Game%26Watch' = 'Mr Game & Watch',
                 'PAC-MAN' = 'Pac Man',
                 'Pac-Man' = 'Pac Man',
                 'PACMAN' = 'Pac Man',
                 'Pok%C3%A9mon Trainer' = 'Pokemon Trainer',
                 'é'  = 'e',
                 'R.O.B.' = 'Rob',
                 'ROB' = 'Rob',
                 'Rosalina' = 'Rosalina & Luma')


char_list = tibble(app_names = c('Mario', 'Donkey Kong', 'Link', 'Samus', 'Dark Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu', 
              'Luigi', 'Ness', 'Captain Falcon', 'Jigglypuff', 'Peach', 'Daisy', 'Bowser', 'Popo', 'Nana',
              'Sheik', 'Zelda', 'Dr Mario', 'Pichu', 'Falco', 'Marth', 'Lucina', 'Young Link', 'Ganondorf', 
              'Mewtwo', 'Roy', 'Chrom', 'Mr Game & Watch', 'Meta Knight', 'Pit', 'Dark Pit', 'Zero Suit Samus',
              'Wario', 'Snake', 'Ike', 'Pokemon Trainer', 'Diddy Kong', 'Lucas', 'Sonic', 'King Dedede', 'Olimar',
              'Lucario', 'Rob', 'Toon Link', 'Wolf', 'Villager', 'Mega Man', 'Wii Fit Trainer', 'Rosalina & Luma',
              'Little Mac', 'Greninja', 'Mii Brawler', 'Mii Swordfighter', 'Mii Gunner', 'Palutena', 'Pac Man', 'Robin',
              'Shulk', 'Bowser Jr', 'Duck Hunt', 'Ryu', 'Ken', 'Cloud', 'Corrin', 'Bayonetta', 'Inkling', 'Ridley', 'Simon',
              'Richter', 'King K Rool', 'Isabelle', 'Incineroar', 'Piranha Plant', 'Joker', 'Hero', 'Banjo & Kazooie', 'Terry', 'Byleth'),
              smash_css_names = c('mario', 'donkey_kong', 'link', 'samus', 'dark_samus', 'yoshi', 'kirby', 'fox', 'pikachu', 'luigi', 
                                     'ness', 'captain_falcon', 'purin', 'peach', 'daisy', 'koopa', 'ice_climber', 'ice_climber',
                                     'sheik', 'zelda', 'dr_mario', 'pichu', 'falco', 'marth', 'lucina', 'young_link','ganondorf', 
                                  'mewtwo', 'roy', 'chrom', 'mr_game_and_watch', 'meta_knight', 'pit', 'black_pit', 
                                  'zero_suit_samus', 'wario', 'snake', 'ike', 'pokemon_trainer', 'diddy_kong', 'lucas', 'sonic', 
                                  'dedede', 'pikmin_and_olimar', 'lucario', 'robot', 'toon_link', 'wolf', 'murabito', 'rockman',
                                  'wii_fit_trainer', 'rosetta_and_chiko', 'little_mac', 'gekkouga', 'mii_fighter', 'mii_fighter', 
                                  'mii_fighter', 'palutena', 'pac_man', 'reflet', 'shulk', 'koopa_jr', 'duck_hunt', 'ryu', 'ken',
                                  'cloud', 'kamui', 'bayonetta', 'inkling', 'ridley', 'simon', 'richter', 'king_k_rool', 'shizue',
                                  'gaogaen', 'packun_flower', 'joker', 'dq_hero', 'banjo_and_kazooie', 'terry', 'byleth'))        

