mapped_names = c("Banjo%26Kazooie" = 'Banjo & Kazooie',
                 'Bowser Jr.' = 'Bowser Jr',
                 'Pit, but edgy' = 'Dark Pit',
                 'Dank Samus' = 'Dark Samus',
                 'Dr. Mario' = 'Dr Mario',
                 'Educated Mario' =  'Dr Mario',
                 'Duck Hunt Duo' = 'Duck Hunt',
                 '^Dedede$' =  'King Dedede',
                 'King K. Rool'  = 'King K Rool',
                 'King KRool'  = 'King K Rool',
                 'Mii Swordspider' = 'Mii Swordfighter',
                 'Mr. Game & Watch' = 'Mr Game & Watch',
                 'M. Game & Watch' = 'Mr Game & Watch',
                 'Mr Game%26Watch' = 'Mr Game & Watch',
                 'PAC-MAN' = 'Pac Man',
                 'Pac-Man' = 'Pac Man',
                 'PACMAN' = 'Pac Man',
                 'Pok%C3%A9mon Trainer' = 'Pokemon Trainer',
                 'R.O.B.' = 'Rob',
                 'ROB' = 'Rob',
                 'Rosalina' = 'Rosalina & Luma')

char_list = c('Bayonetta','Bowser','Bowser Jr','Byleth', 'Captain Falcon','Charizard','Chrom',
              'Cloud','Corrin','Daisy','Dark Pit','Dark Samus','Diddy Kong','Donkey Kong',
              'Dr Mario', 'Duck Hunt','Falco','Fox','Ganondorf','Greninja','Hero','Ice Climbers', 'Ike',
              'Incineroar','Inkling','Isabelle','Ivysaur','Jigglypuff','Joker','Ken',
              'King Dedede','King K Rool','Kirby','Link','Little Mac','Lucario','Lucas',
              'Lucina','Luigi','Mario','Marth','Mega Man','Meta Knight','Mewtwo','Mii Brawler',
              'Mii Gunner','Mii Swordfighter','Mr Game & Watch','Nana','Ness','Olimar','Pac Man',
              'Palutena','Peach','Pichu','Pikachu','Piranha Plant','Pit','Popo','Richter','Ridley',
              'Rob','Robin','Rosalina & Luma','Roy','Ryu','Samus','Sheik','Shulk','Simon','Snake',
              'Sonic','Squirtle','Terry','Toon Link','Villager','Wario','Wii Fit Trainer','Wolf',
              'Yoshi','Young Link','Zelda','Zero Suit Samus')
